###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "nombre": "Caldo 4 quesos",
    "marca": "Knor",
    "descripcion": "Caldo en polvo sabor 4 quesos",
    "precio": 49.99,
    "stock": 17
}
###
GET http://localhost:9000/api/products HTTP/1.1

###
GET http://localhost:9000/api/products/1 HTTP/1.1
###
PUT http://localhost:9000/api/products/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Caldo de pollo",
    "marca": "Knor",
    "descripcion": "Caldo en polvo de gallina",
    "precio": 49.99,
    "stock": 17
}
###
DELETE  http://localhost:9000/api/products/2 HTTP/1.1
